### ISSUE TITLE
`Cannot read property 'eventHandlers' of undefined` after importing victory-native

### ISSUE THREAD

**Issue by alvaromb** [FormidableLabs/victory-native#256] opened 2018-02-12 10:55 UTC
### The Problem

Error `Cannot read property 'eventHandlers' of undefined` after importing 

```js
import { VictoryBar, VictoryChart } from 'victory-native'
```

Error seems to come from `create-container.js`, specifically in this part

```js
var combineDefaultEvents = function (defaultEvents) {
  // takes a defaultEvents array and returns one equal or lesser length,
  // by combining any events that have the same target
  var eventsByTarget = _groupBy(defaultEvents, "target");
  return _toPairs(eventsByTarget).map(function (_ref) {
    var _ref2 = _slicedToArray(_ref, 2),
        target = _ref2[0],
        eventsArray = _ref2[1];

    return {
      target: target,
      eventHandlers: combineEventHandlers(eventsArray.map(function (event) {
        // This line produces the error
        return event.eventHandlers;
      }))
      // note: does not currently handle eventKey or childName
    };
  });
};
```

### Reproduction

Just

```js
import { VictoryBar, VictoryChart } from 'victory-native'
```

| **Package** | **Version** |
| --- | --- |
| `react-native` | `0.52.1` |
| `react` | `16.2.0` |
| `react-native-svg` | `6.1.3` |
| `victory-native` | `0.17.0` |

**Comment by ryan-roemer** [comment] 2018-02-12 16:33
Not a `victory-native` bug and duplicate of https://github.com/FormidableLabs/victory-chart/pull/566 fixed in https://github.com/FormidableLabs/victory-chart/pull/569/files

Please try updating. Thanks!

**Closed by ryan-roemer** 2018-02-12 16:33 UTC
Labels: duplicate

**Comment by alvaromb** [comment] 2018-02-12 16:36
Thanks @ryan-roemer!

Everything works fine now.
