### ISSUE TITLE
Error with VictoryLegend

### ISSUE THREAD

**Issue by luco** [FormidableLabs/victory-native#169] opened 2017-10-26 14:07 UTC
I'm getting a issue here with VictoryLegend. It gives me this:

![image](https://user-images.githubusercontent.com/246373/32057480-2a6bc1fa-ba46-11e7-82e9-229825f2196f.png)

Here's the code:

```
<VictoryLegend x={125} y={10}
				  orientation="horizontal"
				  gutter={20}
				  style={{ border: { stroke: "black" } }}
				  colorScale={[ "navy", "blue", "cyan" ]}
				  data={[
				    { name: "One" }, { name: "Two" }, { name: "Three" }
				  ]}
				/>
```

Thoughts?

Thanks!

**Comment by boygirl** [comment] 2017-11-10 21:07
@luco I'm not able to reproduce this issue. I believe it is fixed in `victory-native@0.16.0`. I'm going to close this issue, but I will reopen it if you find your problem is persisting in the latest version.

**Closed by boygirl** 2017-11-10 21:07 UTC
