### ISSUE TITLE
y axis tickvalue not displaying properly

### ISSUE THREAD

**Issue by yogeshR5** [FormidableLabs/victory-native#323] opened 2018-06-14 12:20 UTC
y axis tickvalue not displaying properly

I added the screenshot link https://prnt.sc/juw8n9

### Checklist

* [ ] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [ ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [ ] I am using the latest version of `victory-native`

* [ ] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [ ] I've searched open issues to make sure I'm not opening a duplicate issue

y axis tickvalue not displaying properly.

I added the screenshot link https://prnt.sc/juw8n9

Describe the issue you're seeing, and what you expect the behavior to be.

i want display tickvalue properly

I added the screenshot link https://prnt.sc/juw8n9

Please check that your issue is specific to `victory-native`. If you're unsure, a good way to check is by trying your code in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started. Issues that are not specific to `victory-native` should be reported [here](https://github.com/FormidableLabs/victory/issues/new).

Please list steps to reproduce your issue. Include a code sample and exact version numbers for `victory-native`, `react-native` and `react-native-svg`.

# Feature Requests

"react-native": "0.55.4",
"victory-native": "^0.18.0"
"react-native-svg": "^6.3.1",

I added the screenshot link https://prnt.sc/juw8n9

### Checklist

* [ ] My feature request is specific to `victory-native`. (Feature requests that do not _specifically_ address native functionality should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [ ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description
I added the screenshot link https://prnt.sc/juw8n9

Please describe the feature you're requesting in detail.

**Comment by boygirl** [comment] 2018-06-14 19:40
`victory-native@~0.18.0` requires `react-native-svg@6.1.x`

**Comment by boygirl** [comment] 2018-06-29 16:46
@yogeshR5 I have not been able to reproduce your issue. It will help if you can provide more information.

- Are you seeing this on all charts?
- Does it look correct if you remove `tickValues`?
- Can you provide code for the whole chart that looks broken so that I can try to reproduce it locally?

**Comment by yogeshR5** [comment] 2018-07-02 04:06
@boygirl 
yes without tick value  working fine.

import {
  VictoryChart,
  VictoryLine,
  VictoryTheme,
  VictoryAxis,
  VictoryScatter,
  VictoryVoronoiContainer,
  VictoryTooltip,
  VictoryClipContainer
} from "victory-native";

<View>
                <VictoryChart
                  padding={{ top: 60, bottom: 30, left: 50, right: 70 }}
                  height={300}
                  containerComponent={
                    <VictoryVoronoiContainer
                      dimension="x"
                      labels={finalData =>
                        finalData.l
                          ? finalData.y.toFixed(2) + " " + finalData.x
                          : null
                      }
                    />
                  }
                >
                  <VictoryLine
                    interpolation="natural"
                    data={finalData}
                    groupComponent={<G />}
                    style={{
                      data: {
                        stroke: `rgba(192,192,192, ${(opacity = 0.3)})`,
                        strokeWidth: 3
                      }
                    }}
                  />

                  <VictoryScatter
                    data={fiveDaysScortData}
                    size={4}
                    style={{ data: { fill: "#fff" } }}
                  />

                  <VictoryAxis
                    dependentAxis
                    width={300}
                    height={400}
                    orientation="right"
                    standalone={false}
                    style={{
                      tickLabels: {
                        fontFamily: "Lato-Bold",
                        fontSize: 12,
                        fill: "#fff",
                        padding: 12
                      },
                      axis: {
                        stroke: "none",
                        verticalAnchor: "middle",
                        textAnchor: "start"
                      }
                    }}
                  />

                  <VictoryAxis
                    crossAxis={false}
                    width={300}
                    height={400}
                    orientation="bottom"
                    standalone={false}
                    style={{
                      tickLabels: {
                        fontFamily: "Lato-Bold",
                        fontSize: 12,
                        fill: "#fff",
                        padding: 12
                      },
                      axis: { stroke: "none" }
                    }}
                  />
                </VictoryChart>
              </View>

**Comment by yogeshR5** [comment] 2018-07-02 04:31
@boygirl 

[{"x":"25.06","y":197.23014195127,"l":true},{"x":"26.06","y":196.107723410535,"l":true},{"x":"27.06","y":195.506889854353,"l":true},{"x":"28.06","y":193.968851375111,"l":true},{"x":"29.06","y":196.134616827185,"l":true}]


l:true it's used for  VictoryVoronoiContainer it's showing two times on VictoryScatterDot place then only used l:true

**Comment by boygirl** [comment] 2018-07-02 04:43
@yogeshR5, your y values are ~200, so assigning y axis `tickValues={1, 2, 3}]` will result in ticks that are squished together near the bottom of your axis because they are very small compared to the y domain. I think you might be getting confused since your x values are given as strings. Victory converts string values into an integer string map. 

I'm going to close this issue, since it is not an issue with the library, but I am happy help if you have more questions.

**Closed by boygirl** 2018-07-02 04:43 UTC
