### ISSUE TITLE
Custom tooltips making labels disappear in android.

### ISSUE THREAD

**Issue by LaylaCsAvila** [FormidableLabs/victory-native#210] opened 2017-12-14 18:13 UTC
I am trying to do the custom tooltips from the [gallery example](https://formidable.com/open-source/victory/gallery/custom-tooltip-labels/). Apart from not showing the custom tooltips at all, whenever I add labelComponent to my VictoryPie, the other labels disappear.

"react-native": "0.51.0",
"react-native-svg": "^6.0.1-rc.1",
"victory-native": "^0.16.1"

And this is my component:
`import React, { Component } from 'react';
import {Text} from 'react-native';
import {
  Dimensions,
  LayoutAnimation,
  StyleSheet,
  View
} from 'react-native';
import PropTypes from 'prop-types'
import Svg from 'react-native-svg';
import { VictoryPie, VictoryChart, VictoryContainer, VictoryLabel, VictoryTooltip } from 'victory-native';

const data = [
    { plano: "Amil", atendimentos: 21, tooltip: "Amil: 21 atendimentos"},
    { plano: "Sulamérica", atendimentos: 30, tooltip: "Sulamérica: 30 atendimentos"}
  ]

  class CustomLabel extends Component<{}> {

    render() {
      return (
        <Svg>
          <VictoryLabel {...this.props}/>
          <VictoryTooltip
          {...this.props}
          x={200} y={250}
          text={`Qualquer coisa`}
          orientation="top"
          pointerLength={0}
          cornerRadius={50}
          width={100}
          height={100}
          flyoutStyle={{ fill: "black" }}
          />
        </Svg>
      )}

  }

  CustomLabel.defaultEvents = VictoryTooltip.defaultEvents;
  CustomLabel.propTypes = { text: PropTypes.string };

export default class VictoryPieChart extends Component<{}> {

  render () {
    const dimensions = Dimensions.get("window")
    return (
      <View>
        <VictoryPie
          data = {data}
          x="plano"
          y="atendimentos"
          labels = {(d) => d.x}
          labelComponent = {<CustomLabel/>}
          innerRadius = {80}
          containerComponent={<VictoryContainer
            width={dimensions.width}
            justifyContent= "center"/>}
        />
      </View>
    )  }
}`

**Comment by boygirl** [comment] 2017-12-14 19:28
@LaylaCsAvila I think you should be enclosing your labels in a `<G/>` tag rather than an `<Svg/>`

**Comment by LaylaCsAvila** [comment] 2017-12-14 19:43
I have tried that before. This is what happens:
![screenshot from 2017-12-14 17-41-30](https://user-images.githubusercontent.com/29239502/34011112-1781accc-e0f6-11e7-9c3c-8973f77f4631.png)

Also tried <View>, <ScrollView>, and returning as an array. <Svg> was the only thing that worked.

**Comment by boygirl** [comment] 2017-12-14 19:48
@LaylaCsAvila thank you for the information, I will try to reproduce this locally.

**Comment by LaylaCsAvila** [comment] 2017-12-15 20:13
@boygirl I have just realized that I forgot to import `<G>` from react-native-svg. Now that I have it properly set in my component, the app doesn't break anymore, but it still doesn't work as expected:
![screenshot from 2017-12-15 18-12-04](https://user-images.githubusercontent.com/29239502/34058776-7f055196-e1c3-11e7-9925-4bdf379a6dc4.png)
(As you can see, I neither have the labels nor the customLabels showing, and nothing happens if I click it or hover over the chart area).

**Comment by boygirl** [comment] 2017-12-15 20:46
@LaylaCsAvila I'm glad you got it sorted out. Can you try something simple like: 
```
class CustomLabel extends React.Component {
  render() {
    return (
      <G>
        <VictoryLabel {...this.props} style={{ fill: "red", fontSize: 12 }}/>
      </G>
    );
  }
}

...
<VictoryPie
  data = {data}
  x="plano"
  y="atendimentos"
  labels = {(d) => d.x}
  labelComponent = {<CustomLabel/>}
/>
```

**Comment by LaylaCsAvila** [comment] 2017-12-15 22:02
I have changed my render() methods to your code. I can see the red labels now, but still no customTooltips:
![screenshot from 2017-12-15 20-02-32](https://user-images.githubusercontent.com/29239502/34062281-e7817812-e1d2-11e7-8696-8b59698923de.png)

**Comment by boygirl** [comment] 2017-12-16 00:02
@LaylaCsAvila you can manually set the `active` prop on the tooltips you are rendering to determine whether the problem is with the events or the positioning.

**Comment by LaylaCsAvila** [comment] 2017-12-18 16:55
I changed the tooltips code to :
`class CustomLabel extends Component<{}> {

    render() {
      return (
        <G>
        <VictoryLabel {...this.props} style={{ fill: "red", fontSize: 12 }} active={true}/>
        </G>)
    }`
But it gives me the same exactly result as before. I can see the red labels, but nothing happens when I try to click it/go over it.

**Comment by LaylaCsAvila** [comment] 2017-12-19 17:22
As shown in the first message, I have:
`CustomLabel.defaultEvents = VictoryTooltip.defaultEvents;
CustomLabel.propTypes = { text: PropTypes.string };`

I just want to replicate the behaviour of the example in the gallery in my app, but even using the same code, I can't make it happen.

**Comment by boygirl** [comment] 2017-12-19 18:50
@LaylaCsAvila I just pushed a fix that might have been effecting the functionality of your tooltips. Can you try `victory-native@0.16.4`

**Comment by boygirl** [comment] 2017-12-20 20:29
@LaylaCsAvila I'm going to close this issue, but let me know if you still can't get it working in the latest version.

**Closed by boygirl** 2017-12-20 20:29 UTC
