### ISSUE TITLE
LinearGradient does not work

### ISSUE THREAD

**Issue by alexsmartens** [FormidableLabs/victory-native#408] opened 2018-11-06 15:56 UTC
### The Problem

I am trying to replicate this [example of using LineGradient](https://formidable.com/open-source/victory/docs/faq/#how-can-i-use-gradient-fills-in-victory), however the gradient just turns black, like this:

![screenshot_20181106-104605](https://user-images.githubusercontent.com/26261714/48075626-af38db00-e1b1-11e8-975c-610e49c4cc77.png)

### Reproduction

Here is my code:
```
<Svg style={{ height: 0, width: 0 }}>
    <Defs>
      <LinearGradient id="myGradient">
        <Stop offset="0%" stopColor="red"/>
        <Stop offset="25%" stopColor="orange"/>
        <Stop offset="50%" stopColor="gold"/>
        <Stop offset="75%" stopColor="yellow"/>
        <Stop offset="100%" stopColor="green"/>
      </LinearGradient>
    </Defs>
  </Svg>
  <VictoryChart>
    <VictoryArea
      style={{
        data: {fill: "url(#myGradient)"}
      }}
      data={[
        { x: 1, y: 2 },
        { x: 2, y: 3 },
        { x: 3, y: 7 },
        { x: 4, y: 4 },
        { x: 5, y: 5 }
      ]}
    />
  </VictoryChart>
```

What do you think?

**Comment by boygirl** [comment] 2018-11-07 22:50
@alexsmartens I'm going to close this issue as a duplicate of https://github.com/FormidableLabs/victory-native/issues/285

You might try work arounds suggested by the other users. You might also look into the differences in implementation between normal svg and `react-native-svg`. Unfortunately, this is not something I'm sure `victory-native` can specifically address, since we don't do anything with gradients within the library itself.

**Closed by boygirl** 2018-11-07 22:50 UTC

**Comment by alexsmartens** [comment] 2018-11-08 12:54
@boygirl,
this is not a duplicate of #285 and the workaround suggested by @cotorusso94 does not help me

**Comment by bear-junior** [comment] 2018-11-16 19:40
@alexsmartens how could it work if you put width and height = 0 to SVG element? 

`<Svg style={{ height: 0, width: 0 }}>`

Your gradient has now height and width = 0px, so you can't see any colors. Remove SVG element and replace with <G> element or put width and height.

**Comment by jemmyphan** [comment] 2019-07-16 07:31
using G instead of Svg as @chiformihai suggested works.
also, make sure that you put G inside of VictoryChart

```
<VictoryChart>
  <G style={{ height: 0, width: 0 }}>
    <Defs>
      <LinearGradient id="myGradient">
        <Stop offset="0%" stopColor="red"/>
        <Stop offset="25%" stopColor="orange"/>
        <Stop offset="50%" stopColor="gold"/>
        <Stop offset="75%" stopColor="yellow"/>
        <Stop offset="100%" stopColor="green"/>
      </LinearGradient>
    </Defs>
  </G>
  <VictoryArea
      style={{
        data: {fill: "url(#myGradient)"}
      }}
      data={[
        { x: 1, y: 2 },
        { x: 2, y: 3 },
        { x: 3, y: 7 },
        { x: 4, y: 4 },
        { x: 5, y: 5 }
      ]}
  />
 </VictoryChart>
```
