### ISSUE TITLE
tickLabelComponent causes RangeError: Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by levsero** [FormidableLabs/victory-native#171] opened 2017-10-27 17:35 UTC
After updating react native from 48.4 to 49.3 passing in a `VictoryLabel` to `tickLabelComponent` on a `VictoryAxis` now causes a crash.

"react-native-svg": "5.4.2",
"victory-native": "0.14.0"/ "0.15.0"

![image](https://user-images.githubusercontent.com/8944331/32117211-8d3c06e8-bb1b-11e7-9275-b4e97151e620.png)

Minimal code to reproduce the error:
```
<VictoryChart>
    <VictoryAxis tickLabelComponent={<VictoryLabel />} />
</VictoryChart>
```

**Comment by xavierlefevre** [comment] 2017-11-02 13:51
Not only with `tickLabelComponent` unfortunately :

<img width="316" alt="screen shot 2017-11-02 at 14 49 21" src="https://user-images.githubusercontent.com/14938214/32329377-365a3310-bfdd-11e7-9516-be45a07370c4.png">

My graph is quite complex, did not try yet to see which setting/prop/usage could produce this, but we don't use `tickLabelComponent`.

**Comment by tommcgurl** [comment] 2017-11-06 02:00
+1 I'm seeing the same issue with the `tickLabelComponent` on a `VictoryAxis`

**Comment by zivchen** [comment] 2017-11-07 15:26
Happens to me to.
For me its VictoryScatter graph with custom dataComponent.
if i remove the dataComponent its OK

Start to happen when i upgraded to 49.5

**Comment by chkchk** [comment] 2017-11-08 03:23
It happens when I used VictoryBar, add this line solved my issue:

 animate={{duration: 0, onLoad: {duration: 0}}}

**Comment by tommcgurl** [comment] 2017-11-08 13:23
Ya @zivchen I was seeing the same thing. Once I removed the `dataComponent` prop it worked fine. I'll try what @chkchk suggested but I wonder what happens if we require an animation.

**Comment by zivchen** [comment] 2017-11-08 16:11
@chkchk thanks for the rescue!!! it worked.
@tommcgurl - i can do with out animation at the moment, its better then crashing anyway, hope you can do with out too.

**Comment by boygirl** [comment] 2017-12-11 23:09
@levsero @xavierlefevre @tommcgurl @zivchen 

I'm not able to reproduce this issue in the latest version (~0.16.0). I'm going to close this issue, but let me know if the problem persists.

**Closed by boygirl** 2017-12-11 23:09 UTC

**Comment by lukerayman** [comment] 2018-01-23 11:12
I just updated React-Native to 0.49.3 (by updating Expo to 22) and this crash is now a thing in my project. I have updated `victory-native` to 0.16.6, but it didn't solve the problem. However, the hack with animation works. 

Anyways, this problem has not been fixed.

<img width="492" alt="zrzut ekranu 2018-01-23 o 12 11 57" src="https://user-images.githubusercontent.com/1166994/35272756-a1c5e588-0036-11e8-9d53-711e1d909cfe.png">

**Comment by jzhw0130** [comment] 2018-02-05 03:12
@boygirl 

The problem exists on the latest version:
"victory-native": "^0.16.6"
"react-native-svg": "^6.1.3".

Do not set the tickLabelComponent, everything is ok 
```javascript
<VictoryAxis dependentAxis
                    domain={updateDomain.y}
                    tickValues={yValues}
                    orientation='left'
                    standalone={false}
                    style={styles.axisY}
                    // tickLabelComponent={<AxisLabel />}
                />
```
