### ISSUE TITLE
Unable to resolve module lodash/object/defaults

### ISSUE THREAD

**Issue by tiensonqin** [FormidableLabs/victory-native#21] opened 2016-09-26 04:01 UTC
Tried `npm cache clean && watchman watch-del-all && rm -rf node_modules && npm install`,
still not works.

Dependencies:

``` json
{
    "@exponent/ex-navigation": "^1.5.9",
    "@exponent/samples": "^1.0.2",
    "@exponent/vector-icons": "^1.0.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "exponent": "10.0.0",
    "lodash": "^4.13.1",
    "react": "~15.3.1",
    "react-native": "github:exponentjs/react-native#sdk-10.0.0",
    "victory-chart-native": "github:formidablelabs/victory-chart-native#a5ba56e"
  }
```

Error message:
Unable to resolve module lodash/object/defaults from /Users/tienson/codes/lymchat/lymchat/node_modules/victory-chart/src/components/victory-chart/victory-chart.js: Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/lodash/object/defaults and its parent directories This might be related to https://github.com/facebook/react-native/issues/4968 To resolve try the following: 1. Clear watchman watches: `watchman watch-del-all`. 2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`. 3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.

**Comment by jevakallio** [comment] 2016-09-29 13:08
I am able to reproduce this, although in my case the failing module is `lodash/object/assign`, being required from `/Users/node_modules` instead from the project directory. The issue indeed seems to be same or similar to https://github.com/facebook/react-native/issues/4968.

This is not a bug in Victory in particular. I believe the amount of packages, or some particular combination of packages in @tiensonqin's example triggers an issue in npm. I have seen similar issues before with lodash and npm3 in particular. Possibly same as https://github.com/npm/npm/issues/10727

Doing a full rimraf and reinstall of `node_modules` did not fix the issue, likely because this set of dependencies causes the install issue to happen repeatably. 

I was able to work around it by killing the packager process and running a the following series of commands.
```
watchman watch-del-all
npm cache clean
rm -rf node_modules/lodash node_modules/lodash*
npm install
./node_modules/react-native/packager/packager.sh --reset-cache
```

Installing with minimal dependencies seems to work reliably (tried a few times, got a working build every time):
```
  "dependencies": {
    "react": "15.3.2",
    "react-native": "0.34.0",
    "victory-chart-native": "github:formidablelabs/victory-chart-native#a5ba56e",
    "react-native-svg": "^4.3.1"
  }
```

**Comment by ryan-roemer** [comment] 2016-09-29 13:31
@jevakallio - you can confirm the NPM issue if a _second_ 'npm install' command installs _more_ midules

**Comment by jevakallio** [comment] 2016-09-29 14:44
I don't get new modules on the second install.

The case doesn't seem to be easily reproducible. Running clean install and starting up the react packager occasionally succeeds but occasionally fails.

**Comment by evollu** [comment] 2016-10-01 13:16
i have the same issue

**Comment by evollu** [comment] 2016-10-01 13:37
I fixed by `npm i victory-core victory-chart --save`.
looks like if the dependency is buried too deep npm won't find it

**Comment by evollu** [comment] 2016-10-03 21:47
got the error again. @jevakallio have you found a fix?

**Comment by jevakallio** [comment] 2016-10-04 16:56
@evollu I am seeing this now with other victory native based projects as well, so we need a resolution. Haven't found one yet.

**Comment by jevakallio** [comment] 2016-10-04 18:55
As a workaround, it seems that starting the react native packager with `--reset-cache` fixes the issue for me. Still investigating root cause.
```
./node_modules/react-native/packager/packager.sh --reset-cache
```

**Comment by allpwrfulroot** [comment] 2017-01-07 22:35
Using Exponent (v12) and unable to install, errors like: "Unable to resolve module", "Module does not exist".

**Comment by chrisbolin** [comment] 2017-04-22 11:44
closing this as it seems to not be victory specific

**Closed by chrisbolin** 2017-04-22 11:44 UTC

**Comment by 9128343207** [comment] 2018-10-14 11:15
[16:37:15] Failed building JavaScript bundle.
[16:38:22] Unable to resolve "./_DataView" from "node_modules/lodash/_getTag.js"

getiing above error in expo after installing lodash...
