### ISSUE TITLE
victory-native is not compatible with react-native^0.56

### ISSUE THREAD

**Issue by lukasa1993** [FormidableLabs/victory-native#332] opened 2018-07-04 10:54 UTC
```
2018-07-04 14:53:41.838 [error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating '_victoryContainer.default')
2018-07-04 14:53:41.844 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating '_victoryContainer.default')
```

trying to run sample charts inside existing project this is what i cat as soon as i import it

**Comment by lukasa1993** [comment] 2018-07-04 11:50
as i dig in think its `babel 7` thing

**Comment by konzertimpo** [comment] 2018-07-04 22:58
I had the same issue a few hours ago. Which react-native version do you use?

In my case, I got the error with react-native 0.56. After the downgrade to version 0.55.x my project worked again.

I was happy and didn't do any further researches, but I think that victory-native is not compatible with react-native 0.56

**Comment by lukasa1993** [comment] 2018-07-05 05:04
yes i am using 0.56 and they switched to babel 7 there so thats must be a problem

**Comment by niocncn** [comment] 2018-07-06 12:20
have the same issue on RN 0.56

**Comment by inkweon7269** [comment] 2018-07-07 07:11
me too, Same Issue~!
<img width="1440" alt="2018-07-07 4 10 47" src="https://user-images.githubusercontent.com/9918075/42407958-52520058-8200-11e8-99c7-27bf9459be3f.png">

**Comment by VicFrolov** [comment] 2018-07-09 18:52
Any ETA on a fix for this?

**Comment by nikolas7892** [comment] 2018-07-09 18:54
I tried cloning this project and upgrading the dependencies. Seems like the way the startup script is setup is dependent upon starting the packager in a way that does not exist anymore. I really need this.

**Comment by boygirl** [comment] 2018-07-09 19:50
Thank you all for identifying the cause of this issue. I updated the issue title to reflect the new information, but I won't be able to upgrade until next week. If anyone else would like to open a PR, I would greatly appreciate it.

**Comment by sdroadie** [comment] 2018-07-12 23:56
I managed to clone the project, updated to `react-native@^0.56.0`, `@babel/core@^7.0.0-beta.53`, and `babel-preset-react-native@^5.0.2` in `devDependencies, and changed the start command to `node node_modules/react-native/local-cli/cli.js start`. I'm able to get the demo project running, but am still seeing the `undefined is not an object (evaluating '_victoryContainer.default')`.

**Comment by boygirl** [comment] 2018-07-13 00:55
@sdroadie then... it sounds like the bigger issue is the babel 7 upgrade. All of the main victory repos build `lib/` and `es/` targets with babel 6, and `victory-native` requires components form the main repos  like: 
`import { VictoryContainer } from "victory-core/es";`

I am in the middle of some major infrastructure work in the main repos. I will see if I can update our build infrastructure to use babel 7 while I'm at it. I expect all this work to land by Tuesday.

**Comment by ganisback** [comment] 2018-07-18 05:41
@boygirl, any update on this issue? thanks for your hard work.

**Comment by boygirl** [comment] 2018-07-20 05:58
Update: 

After upgrading to Babel 7 in the main `victory` packages, I'm still hitting the same issue @sdroadie mentions in `react-native@^0.56.0`. I'm afraid this is going to take a few more days to solve. Thanks for your patience, everyone.

**Comment by boygirl** [comment] 2018-07-20 06:04
Update 2: 

The issue is confined to the native version of the `createContainer` helper. Since I've narrowed it down, I think I can have this fixed by Monday.

**Comment by horou-sk** [comment] 2018-07-20 06:26
me too, Same Issue.
![image](https://user-images.githubusercontent.com/10435269/42986430-23e0d348-8c28-11e8-8215-52a1417da955.png)
but I changed this code
![image](https://user-images.githubusercontent.com/10435269/42986528-6e954036-8c28-11e8-8e84-20e254254a30.png)
to `import VictoryContainer from "../components/victory-container";`
It's running normally.

**Comment by boygirl** [comment] 2018-07-23 06:37
Update:

I have done some refactoring to solve the underlying import issue that was causing issues with babel 7 + `react-native@0.56`. With Victory's move to much more modular packages in v30.0.0, it was a bit more complex than changing `import VictoryContainer from "../components/victory-container";`

Demos are all running as expected, but `babel-preset-react-native@^5.0.0` has totally broken test infrastructure. https://github.com/FormidableLabs/victory-native/pull/347

I'm working on tracking that down, but I think this improvement will be further delayed by a day or two. In the meantime, if anyone has insight into the breaking changes in `babel-preset-react-native@^5.0.0` please let me know

**Comment by ganisback** [comment] 2018-07-23 09:01
thanks @boygirl, i will try on it.

**Comment by boygirl** [comment] 2018-07-23 18:04
Update!

Using `metro-react-native-babel-preset` for compiling code for testing only. New version will be published within the hour as `victory-native@30.0.0`. The reason for this major version bump is to conform to other victory packages. You can read about the rationale here: https://formidable.com/blog/2018/victory-is-turning-thirty/

**Closed** 2018-07-23 18:06 UTC

**Comment by boygirl** [comment] 2018-07-23 18:17
This work is published as `victory-native@30.0.0`

Thank you to everyone in this thread for their help and patience!

**Comment by jussellymoreno1394** [comment] 2019-06-06 20:26
@boygirl Excelent

This work for me. Thank you so much.

**Comment by Subway19** [comment] 2019-07-24 11:48
Excellent. Worked for me
