### ISSUE TITLE
Cannot rotate axis label.

### ISSUE THREAD

**Issue by ericschaal** [FormidableLabs/victory-native#133] opened 2017-07-25 13:27 UTC
Hi everyone,

I am trying to rotate an axis label using `style={{axisLabel: {angle: 90}}}` on victory-axis but it is not rotating. I also tried using `axisLabelComponent={<VictoryLabel angle={90}/>}` without success.

Thanks!

**Comment by johanolandero** [comment] 2017-07-25 15:36
Hello!

Try specifying the angle in the axisLabel object within the style like so.

<img width="796" alt="rotatedlabel" src="https://user-images.githubusercontent.com/23318359/28580344-7e2b31fc-715f-11e7-8f4c-8d3859500e99.png">

**Comment by ericschaal** [comment] 2017-07-25 16:16
Hi! 
Thank you for your answer,
I think that's what I already had. Unless I have a vision problem hahaha.
![untitled](https://user-images.githubusercontent.com/14843031/28582317-f19aec04-7132-11e7-9d92-a81e2a7faddb.jpeg)

**Comment by boygirl** [comment] 2017-07-25 16:23
@ericschaal unfortunately this is an issue in `react-native-svg` that we haven't figured out how to deal with yet. I'm going to close this issue as a duplicate of https://github.com/FormidableLabs/victory-native/issues/103

**Closed by boygirl** 2017-07-25 16:23 UTC

**Comment by i-schuetz** [comment] 2019-01-29 14:32
Is it possible to set the anchor of the rotation of move the labels somehow, such that after being rotated their center aligns with the data point's center? I tried with properties like `paddingLeft` or `marginLeft` but they don't have any effect.
