### ISSUE TITLE
ExceptionsManager.js:65 Tried to register two views with the same name RNSVGPath (ERROR)

### ISSUE THREAD

**Issue by nwabdou85** [FormidableLabs/victory-native#208] opened 2017-12-14 12:54 UTC
I tried to use victory-native on my app; bu throw me this error

`ExceptionsManager.js:65 Tried to register two views with the same name RNSVGPath 
``Module AppRegistry is not a registered callable module (calling runApplication)`

this is my json 

`  "dependencies": {
    "AsyncStorage": "^0.1.5",
    "expo": "^22.0.0",
    "moment": "^2.19.3",
    "react": "16.0.0",
    "react-native": "0.49.0",
    "react-native-material-ui": "^1.14.0",
    "react-native-pathjs-charts": "0.0.33",
    "react-native-sticky-header-footer-scroll-view": "^2.1.3",
    "react-native-svg": "^6.0.1-rc.1",
    "react-navigation": "^1.0.0-beta.21",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "victory-native": "^0.16.1"
  }`

Any solution to fix it ?

Thank's

**Comment by boygirl** [comment] 2017-12-14 19:47
@nwabdou85 it's a little hard to diagnose with just that. Are you getting that error from just adding `victory-native` as a dependency? If not, can you show the code?

Also, `victory-native@0.16.0` should be used with `react-native@^0.50.0`

**Comment by boygirl** [comment] 2017-12-18 23:47
@nwabdou85 I'm closing this issue for now, as I can't reproduce

**Closed by boygirl** 2017-12-18 23:47 UTC

**Comment by nwabdou85** [comment] 2017-12-20 15:32
@boygirl  sorry for delay; I ll retry it very soon and update you with more details as I handle another issue before that.

**Comment by Oakyden** [comment] 2019-01-02 15:11
I believe this is because expo now includes the package react-native-svg as a dependency.


If you run 

_npm list react-native react-native-svg_ 

You'll probably see it listed twice with two versions, one being under expo.

Essentially any expo users need to npm uninstall react-native-svg and then any code that imports FROM react-native-svg, needs to be changed to FROM expo.

I'm not sure if this is possible or an easy win
