### ISSUE TITLE
<VictoryChart>  throws error on android but works fine on iOS

### ISSUE THREAD

**Issue by UtkarshPramodGupta** [FormidableLabs/victory-native#50] opened 2017-02-21 07:29 UTC
When I used Victory Chart and a few other components of Victory native in my code it throws an error on my android emulator as shown in the below picture. But, it runs fine on iOS:
_
<img width="341" alt="screen shot 2017-02-21 at 12 54 26 pm" src="https://cloud.githubusercontent.com/assets/11005608/23154654/fad51bfe-f834-11e6-8c98-d3d6e9a374bb.png">
_

**Comment by aperreaultTRU** [comment] 2017-02-22 02:26
I'm getting the same issue.

**Comment by guitoof** [comment] 2017-03-02 10:28
Hi there I get the exact same issue. There seems to be a version conflict between react-native-svg and react-native 
Which version of React Native do you use ?
I had this error with 
```
"react-native": "0.41.2",
"react-native-svg": "^5.1.5",
```

**Comment by guitoof** [comment] 2017-03-02 11:06
Hi there,
I think I found what was wrong with the TextShadowNode cast.
I created a PR here to fix it: https://github.com/react-native-community/react-native-svg/pull/268

 If it cannot be merged for some reason, do not hesitate to use our fork: https://github.com/bamlab/react-native-svg

**Comment by AlanFoster** [comment] 2017-03-12 01:34
Confirmed working with @guitoof's branch -

> yarn add bamlab/react-native-svg

**Comment by browniefed** [comment] 2017-03-15 15:29
Looks like this is a `victory-native` issue. Somewhere a `Text` component is being rendered from `react-native` instead of `react-native-svg` (according to the bug filed there)

**Closed** 2019-03-16 00:00 UTC
