### ISSUE TITLE
Y-axis label not align equally

### ISSUE THREAD

**Issue by yogeshR5** [FormidableLabs/victory-native#321] opened 2018-06-13 14:44 UTC
# Bugs and Questions

i attached screenshot link https://prnt.sc/juinsk

* [ ] This is a `victory-native` specific issue. (Issues that _also_ appear in `victory` should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [ ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [ ] I am using the latest version of `victory-native`

* [ ] I have checked to make sure that my versions of `react-native` and `react-native-svg` are compatible with this version of `victory-native`. [Read about version requirements](https://github.com/FormidableLabs/victory-native/blob/master/README.md#peer-dependencies-and-version-requirements)

* [ ] I've searched open issues to make sure I'm not opening a duplicate issue

Y-axis label does not align equally. I attached image

Describe the issue you're seeing, and what you expect the behavior to be.

i want to align labels to equal to the grid line

i attached screenshot link https://prnt.sc/juinsk

Please check that your issue is specific to `victory-native`. If you're unsure, a good way to check is by trying your code in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started. Issues that are not specific to `victory-native` should be reported [here](https://github.com/FormidableLabs/victory/issues/new).

Please list steps to reproduce your issue. Include a code sample and exact version numbers for `victory-native`, `react-native` and `react-native-svg`.

# Feature Requests

i want to align labels to equal to the grid line

i attached screenshot link https://prnt.sc/juinsk

* [ ] My feature request is specific to `victory-native`. (Feature requests that do not _specifically_ address native functionality should be opened [here](https://github.com/FormidableLabs/victory/issues/new))

* [ ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.
 
i attached screenshot link https://prnt.sc/juinsk

**Comment by boygirl** [comment] 2018-06-13 19:30
Please include exact version numbers for `victory-native`, `react-native` and `react-native-svg`. I suspect that the issue you're seeing is related to a version mismatch between `victory-native` and `react-native-svg`.

**Comment by yogeshR5** [comment] 2018-06-14 04:08
@boygirl  Thanks for your response.

"react-native": "0.55.4",
"victory-native": "^0.18.0"
"react-native-svg": "^5.3.0",

and here is my code .
  <VictoryChart>
  <VictoryLine
            style={{
              data: { stroke: "#28275A" },
              parent: { border: "100px solid #000" }
            }}
            data={[
              { x: 1, y: 2 },
              { x: 2, y: 3 },
              { x: 3, y: 5 },
              { x: 4, y: 4 },
              { x: 5, y: 6 }
            ]}
          />
        </VictoryChart>

**Comment by boygirl** [comment] 2018-06-29 16:43
closing as a duplicate of https://github.com/FormidableLabs/victory-native/issues/323

**Closed by boygirl** 2018-06-29 16:43 UTC
