### ISSUE TITLE
No component found for view with name "RNSVGViewBox" error 

### ISSUE THREAD

**Issue by haifaGh** [FormidableLabs/victory-native#108] opened 2017-06-16 00:41 UTC
Hi, i just followed the documentation and installed victory native via npm, i also installed react-native-svg and linked it. 
I keep getting this error although i'm following this https://formidable.com/open-source/victory/docs/native and i just started by the first example. 
According to the documentation 
<img width="747" alt="screen shot 2017-06-16 at 01 38 21" src="https://user-images.githubusercontent.com/15948361/27207175-88522b3a-5234-11e7-94b8-b5867ce1a691.png">
  and since i'm using react native 0.42.0 and react 15.4.2 so i installed react-native-svg 4.5.0 but it's not working and i get this 
<img width="369" alt="screen shot 2017-06-16 at 01 13 37" src="https://user-images.githubusercontent.com/15948361/27207193-b48c68e6-5234-11e7-9dcd-be9595912647.png">
I tried to uninstall it and unlink it and i changed to the newer version but still getting the same error. 
Maybe this is not a react-native-svg issue and it's a victory-native issue .. So can you please help me fix this issue ... thanks :)

**Comment by chrisbolin** [comment] 2017-06-16 16:41
hey @haifaGh! I'm sorry about the annoy issue. This is definitely related to react-native-svg (victory-native's key dependency!)

What I'm _guessing_ is that multiple versions of react-native-svg are installed for your project. could you do a `yarn list` or `npm list` and tell me which react-native-svg lines show up?

**Comment by haifaGh** [comment] 2017-06-16 20:28
thanks @chrisbolin here is the result of npm list 
<img width="367" alt="screen shot 2017-06-16 at 21 27 24" src="https://user-images.githubusercontent.com/15948361/27243629-c217c478-52da-11e7-8152-541edffc18bf.png">

**Comment by chrisbolin** [comment] 2017-06-17 09:51
Hmm, that seems to check out, assuming `react-native` between `0.40.0` and `0.44.0`. Honestly I would try the annoying (and all-too-common) react-native debug steps:
`watchman watch-del-all`
`rm -rf node_modules/` 
`./node_modules/react-native/packager/packager.sh --reset-cache`

If your project is new or flexible, I'd also recommend at least trying a more recent versions of `react-native` and `react-native-svg`. At least half of the victory-native bugs are react-native-svg bugs that get fixed in updates :) 

For our part, I'll call out the dependency on react-native-svg (and its persnickety versioning) explicitly in the victory-native readme and the tutorial.

**Comment by chrisbolin** [comment] 2017-06-17 10:12
@haifaGh I want to apologize for the out-of-date tutorial. I'm trying these issues in https://github.com/FormidableLabs/victory-native/issues/109 and working to fix them now 👍

**Comment by haifaGh** [comment] 2017-06-17 10:26
ok thank you @chrisbolin

**Comment by chrisbolin** [comment] 2017-06-17 10:47
I'm going to close this issue, as it _seems_ like the root cause is react-native-svg. I'm tracking our documentation issues/errors related to this in #109. If it looks like we have a dependency issue in `victory-native` itself I'll reopen this issue.

**Comment by chrisbolin** [comment] 2017-06-17 10:47
@haifaGh totally happy to keep helping you get set up though, so we can use this thread for that :)

**Closed by chrisbolin** 2017-06-17 10:47 UTC

**Comment by edencakir** [comment] 2017-07-01 14:20
I'm having the same issue with RN version 0.45.1, exactly same errors.

**Comment by chrisbolin** [comment] 2017-07-01 19:23
Thanks for the update, @edencakir! These troubleshooting notes are helpful to others googling the error.
